import Foundation
import ArgumentParser
import SwiftSlides

actor PresentationRegistry: Sendable {
    static let shared = PresentationRegistry()
    
    private var registry: [String: @Sendable () -> any Presentation] = [:]
    
    private init() {}
    
    func register(_ factory: @escaping @Sendable () -> any Presentation, name: String) {
        registry[name] = factory
    }
    
    func unregister(_ name: String) {
        registry.removeValue(forKey: name)
    }
    
    subscript(_ name: String) -> (@Sendable () -> any Presentation)? {
        registry[name]
    }
    
    func getAllPresentations() -> [String] {
        Array(registry.keys)
    }
}

struct DemoPresentation: Presentation {
    let id = UUID()
    var title: String
    var author: String?
    var sections: [any Section]
    var theme: 主题?
    
    init() {
        self.title = "Demo Presentation"
        self.author = "SwiftOffice"
        self.theme = nil
        self.sections = [
            章节(标题: "Introduction", slides: [
                封面页(标题: "Welcome", 副标题: "Demo Presentation"),
                列表页(标题: "About", 项目: ["This is a demo presentation", "Generated by SwiftOffice CLI"]),
            ]),
            章节(标题: "Features", slides: [
                列表页(标题: "Feature 1", 项目: ["Easy to use"]),
                列表页(标题: "Feature 2", 项目: ["Fast generation"]),
            ]),
        ]
    }
}

struct SimpleDemo: Presentation {
    let id = UUID()
    var title: String
    var author: String?
    var sections: [any Section]
    var theme: 主题?
    
    init() {
        self.title = "Simple Demo"
        self.author = "SwiftOffice"
        self.theme = nil
        self.sections = [
            章节(标题: "Start", slides: [
                封面页(标题: "Simple Demo", 副标题: "Minimal Example"),
            ]),
        ]
    }
}

@main
struct SwiftOfficeCLI: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "swiftoffice",
        abstract: "Swift Office CLI Tool - Generate office documents from Swift structs"
    )
    
    @Argument(help: "The presentation struct name")
    var structName: String
    
    @Option(name: .shortAndLong, help: "Output file path (default: <structName>.pptx)")
    var output: String?
    
    @Flag(name: .shortAndLong, help: "Verbose output")
    var verbose: Bool = false
    
    func run() async throws {
        await PresentationRegistry.shared.register({ DemoPresentation() }, name: "DemoPresentation")
        await PresentationRegistry.shared.register({ SimpleDemo() }, name: "SimpleDemo")
        
        print("Looking for presentation: \(structName)")
        
        guard let factory = await PresentationRegistry.shared[structName] else {
            print("Error: Unknown presentation '\(structName)'")
            print("\nAvailable presentations:")
            for name in await PresentationRegistry.shared.getAllPresentations().sorted() {
                print("  • \(name)")
            }
            throw ExitCode.failure
        }
        
        let presentation = factory()
        let outputPath = output ?? "\(structName).pptx"
        
        if verbose {
            print("Generating: \(presentation.title)")
            print("Sections: \(presentation.sections.count)")
            print("Total slides: \(presentation.sections.reduce(0) { $0 + $1.slides.count })")
        }
        
        if #available(macOS 10.15, *) {
            try await presentation.toPPTX(outputPath: outputPath)
            print("✓ Generated: \(outputPath)")
        } else {
            print("Error: PPTX generation requires macOS 10.15 or later")
            throw ExitCode.failure
        }
    }
}
